### ISSUE TITLE
Site not responding

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#86] opened 2016-05-16 23:07 UTC
Pages not responding, just entering time stamp for log check. 4:06PM PST 5/16

**Comment by cmazuc** [comment] 2016-05-16 23:08
looks like we just confirmed that the free instance type isn't gonna cut it ;)

should be back up shortly

**Comment by subiki** [comment] 2016-05-16 23:09
How badly was it crushed? Is there any data?

**Comment by cmazuc** [comment] 2016-05-16 23:12
Just went out of memory, the instance only had a gig so no surprises there. Logs are available in the CloudWatch console if you're interested.

I'm taking the opportunity to re-roll the instance, I'll close this out once that is complete.

**Comment by cmazuc** [comment] 2016-05-16 23:19
Just fyi, current architecture is a single EC2 instance with an RDS instance on the backend for the database. I'm also using CloudFront to offload most of the image serving. If we need to scale up it's trivial to add a load balancer and more web server instances. We'll need to move to that sort of setup before we leave beta but hopefully we can get by with just the single instance until we get some feedback on the product.

**Comment by cmazuc** [comment] 2016-05-16 23:24
I moved us from a t2.micro to an m4.large, should work a bit better. It's spinning up now and should be available shortly

**Comment by cmazuc** [comment] 2016-05-16 23:27
Back up

**Closed by cmazuc** 2016-05-16 23:27 UTC
Labels: bug
