### ISSUE TITLE
User session persistence issues

### ISSUE THREAD

**Issue by oamike** [cmazuc/scarfage#154] opened 2016-09-26 00:59 UTC
Provide oauth2 login though FB - as many users will link to scarf age through FB posts - and should maintain login.
Most mobile devices support user login via FB and twitter accounts - and can facilitate login from other apps - of note, links i click from scarfage emails require login each time. This feature may fix that.

Please fill out as much of this as you can

What is your username? oamike

Did you receive a specific error message? No

What was the URL that gave an error? No

Approximately what time did the error occur (please include time zone)?

**Comment by cmazuc** [comment] 2016-09-26 01:19
dupe of #1 

The repeated login thing is most likely me restarting the app and shouldn't happen once I'm not updating it constantly.

**Comment by cmazuc** [comment] 2016-09-28 13:54
I see what you mean with getting logged out a bunch now, definitely not what I thought it was. Hopefully https://github.com/cmazuc/scarfage/commit/a9aee589cec4bc0e023b0d72689636c4effd1769 helps but I'll keep an eye on it

**Comment by cmazuc** [comment] 2016-09-30 00:30
This seems fixed for me, please reopen if you're still getting booted.

**Closed by cmazuc** 2016-09-30 00:30 UTC
Labels: bug
